//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfTwitterStreamingApplication.WcfStreamingServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfStreamingServiceReference.IWcfService", CallbackContract=typeof(WpfTwitterStreamingApplication.WcfStreamingServiceReference.IWcfServiceCallback))]
    public interface IWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/GetStreaming", ReplyAction="http://tempuri.org/IWcfService/GetStreamingResponse")]
        void GetStreaming(string[] filters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/GetStreaming", ReplyAction="http://tempuri.org/IWcfService/GetStreamingResponse")]
        System.Threading.Tasks.Task GetStreamingAsync(string[] filters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/PauseStreaming", ReplyAction="http://tempuri.org/IWcfService/PauseStreamingResponse")]
        void PauseStreaming();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/PauseStreaming", ReplyAction="http://tempuri.org/IWcfService/PauseStreamingResponse")]
        System.Threading.Tasks.Task PauseStreamingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/ResumeStreaming", ReplyAction="http://tempuri.org/IWcfService/ResumeStreamingResponse")]
        void ResumeStreaming();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/ResumeStreaming", ReplyAction="http://tempuri.org/IWcfService/ResumeStreamingResponse")]
        System.Threading.Tasks.Task ResumeStreamingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/StopStreaming", ReplyAction="http://tempuri.org/IWcfService/StopStreamingResponse")]
        void StopStreaming();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/StopStreaming", ReplyAction="http://tempuri.org/IWcfService/StopStreamingResponse")]
        System.Threading.Tasks.Task StopStreamingAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWcfServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/PrintMessage", ReplyAction="http://tempuri.org/IWcfService/PrintMessageResponse")]
        void PrintMessage(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/StreamStarted", ReplyAction="http://tempuri.org/IWcfService/StreamStartedResponse")]
        void StreamStarted();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/StreamPaused", ReplyAction="http://tempuri.org/IWcfService/StreamPausedResponse")]
        void StreamPaused();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/StreamResumed", ReplyAction="http://tempuri.org/IWcfService/StreamResumedResponse")]
        void StreamResumed();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/StreamStopped", ReplyAction="http://tempuri.org/IWcfService/StreamStoppedResponse")]
        void StreamStopped();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWcfServiceChannel : WpfTwitterStreamingApplication.WcfStreamingServiceReference.IWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WcfServiceClient : System.ServiceModel.DuplexClientBase<WpfTwitterStreamingApplication.WcfStreamingServiceReference.IWcfService>, WpfTwitterStreamingApplication.WcfStreamingServiceReference.IWcfService {
        
        public WcfServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public WcfServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public WcfServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public WcfServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public WcfServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void GetStreaming(string[] filters) {
            base.Channel.GetStreaming(filters);
        }
        
        public System.Threading.Tasks.Task GetStreamingAsync(string[] filters) {
            return base.Channel.GetStreamingAsync(filters);
        }
        
        public void PauseStreaming() {
            base.Channel.PauseStreaming();
        }
        
        public System.Threading.Tasks.Task PauseStreamingAsync() {
            return base.Channel.PauseStreamingAsync();
        }
        
        public void ResumeStreaming() {
            base.Channel.ResumeStreaming();
        }
        
        public System.Threading.Tasks.Task ResumeStreamingAsync() {
            return base.Channel.ResumeStreamingAsync();
        }
        
        public void StopStreaming() {
            base.Channel.StopStreaming();
        }
        
        public System.Threading.Tasks.Task StopStreamingAsync() {
            return base.Channel.StopStreamingAsync();
        }
    }
}
